//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", ConfigurationName="RecepcionCfdiService.RecepcionCfdi")]
    public interface RecepcionCfdi {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/verificacionPorQRCodev33Request", ReplyAction="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/verificacionPorQRCodev33Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorQRCodev33Response verificacionPorQRCodev33(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorQRCodev33Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/verificacionPorQRCodev33Request", ReplyAction="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/verificacionPorQRCodev33Response")]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorQRCodev33Response> verificacionPorQRCodev33Async(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorQRCodev33Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/verificacionPorXMLv33Request", ReplyAction="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/verificacionPorXMLv33Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorXMLv33Response verificacionPorXMLv33(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorXMLv33Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/verificacionPorXMLv33Request", ReplyAction="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/verificacionPorXMLv33Response")]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorXMLv33Response> verificacionPorXMLv33Async(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorXMLv33Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/recepcionCfdiMultipleRequest", ReplyAction="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/recepcionCfdiMultipleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiMultipleResponse recepcionCfdiMultiple(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiMultipleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/recepcionCfdiMultipleRequest", ReplyAction="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/recepcionCfdiMultipleResponse")]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiMultipleResponse> recepcionCfdiMultipleAsync(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiMultipleRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/recepcionCfdiRequest", ReplyAction="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/recepcionCfdiResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiResponse recepcionCfdi(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/recepcionCfdiRequest", ReplyAction="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/recepcionCfdiResponse")]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiResponse> recepcionCfdiAsync(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/recepcionCfdiZipRequest", ReplyAction="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/recepcionCfdiZipResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiZipResponse recepcionCfdiZip(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiZipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/recepcionCfdiZipRequest", ReplyAction="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/recepcionCfdiZipResponse")]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiZipResponse> recepcionCfdiZipAsync(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiZipRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/cfdiPorUUIDv33Request", ReplyAction="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/cfdiPorUUIDv33Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorUUIDv33Response cfdiPorUUIDv33(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorUUIDv33Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/cfdiPorUUIDv33Request", ReplyAction="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/cfdiPorUUIDv33Response")]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorUUIDv33Response> cfdiPorUUIDv33Async(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorUUIDv33Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/cfdiPorEtiquetav33Request", ReplyAction="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/cfdiPorEtiquetav33Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorEtiquetav33Response cfdiPorEtiquetav33(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorEtiquetav33Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/cfdiPorEtiquetav33Request", ReplyAction="http://recepcionCfdi.ws.pade.mx/RecepcionCfdi/cfdiPorEtiquetav33Response")]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorEtiquetav33Response> cfdiPorEtiquetav33Async(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorEtiquetav33Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificacionPorQRCodev33", WrapperNamespace="http://recepcionCfdi.ws.pade.mx", IsWrapped=true)]
    public partial class verificacionPorQRCodev33Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string qrCode;
        
        public verificacionPorQRCodev33Request() {
        }
        
        public verificacionPorQRCodev33Request(string contrato, string usuario, string passwd, string qrCode) {
            this.contrato = contrato;
            this.usuario = usuario;
            this.passwd = passwd;
            this.qrCode = qrCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificacionPorQRCodev33Response", WrapperNamespace="http://recepcionCfdi.ws.pade.mx", IsWrapped=true)]
    public partial class verificacionPorQRCodev33Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public verificacionPorQRCodev33Response() {
        }
        
        public verificacionPorQRCodev33Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificacionPorXMLv33", WrapperNamespace="http://recepcionCfdi.ws.pade.mx", IsWrapped=true)]
    public partial class verificacionPorXMLv33Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cfdiXml;
        
        public verificacionPorXMLv33Request() {
        }
        
        public verificacionPorXMLv33Request(string contrato, string usuario, string passwd, string cfdiXml) {
            this.contrato = contrato;
            this.usuario = usuario;
            this.passwd = passwd;
            this.cfdiXml = cfdiXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificacionPorXMLv33Response", WrapperNamespace="http://recepcionCfdi.ws.pade.mx", IsWrapped=true)]
    public partial class verificacionPorXMLv33Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public verificacionPorXMLv33Response() {
        }
        
        public verificacionPorXMLv33Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionCfdiMultiple", WrapperNamespace="http://recepcionCfdi.ws.pade.mx", IsWrapped=true)]
    public partial class recepcionCfdiMultipleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("arregloCfdiXml", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] arregloCfdiXml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("etiquetas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] etiquetas;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool prueba;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] opciones;
        
        public recepcionCfdiMultipleRequest() {
        }
        
        public recepcionCfdiMultipleRequest(string contrato, string usuario, string passwd, string[] arregloCfdiXml, string[] etiquetas, bool prueba, string[] opciones) {
            this.contrato = contrato;
            this.usuario = usuario;
            this.passwd = passwd;
            this.arregloCfdiXml = arregloCfdiXml;
            this.etiquetas = etiquetas;
            this.prueba = prueba;
            this.opciones = opciones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionCfdiMultipleResponse", WrapperNamespace="http://recepcionCfdi.ws.pade.mx", IsWrapped=true)]
    public partial class recepcionCfdiMultipleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public recepcionCfdiMultipleResponse() {
        }
        
        public recepcionCfdiMultipleResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionCfdi", WrapperNamespace="http://recepcionCfdi.ws.pade.mx", IsWrapped=true)]
    public partial class recepcionCfdiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cfdiXml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string etiqueta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool prueba;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] opciones;
        
        public recepcionCfdiRequest() {
        }
        
        public recepcionCfdiRequest(string contrato, string usuario, string passwd, string cfdiXml, string etiqueta, bool prueba, string[] opciones) {
            this.contrato = contrato;
            this.usuario = usuario;
            this.passwd = passwd;
            this.cfdiXml = cfdiXml;
            this.etiqueta = etiqueta;
            this.prueba = prueba;
            this.opciones = opciones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionCfdiResponse", WrapperNamespace="http://recepcionCfdi.ws.pade.mx", IsWrapped=true)]
    public partial class recepcionCfdiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public recepcionCfdiResponse() {
        }
        
        public recepcionCfdiResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionCfdiZip", WrapperNamespace="http://recepcionCfdi.ws.pade.mx", IsWrapped=true)]
    public partial class recepcionCfdiZipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] archivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool prueba;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] opciones;
        
        public recepcionCfdiZipRequest() {
        }
        
        public recepcionCfdiZipRequest(string contrato, string usuario, string passwd, byte[] archivo, bool prueba, string[] opciones) {
            this.contrato = contrato;
            this.usuario = usuario;
            this.passwd = passwd;
            this.archivo = archivo;
            this.prueba = prueba;
            this.opciones = opciones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionCfdiZipResponse", WrapperNamespace="http://recepcionCfdi.ws.pade.mx", IsWrapped=true)]
    public partial class recepcionCfdiZipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public recepcionCfdiZipResponse() {
        }
        
        public recepcionCfdiZipResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cfdiPorUUIDv33", WrapperNamespace="http://recepcionCfdi.ws.pade.mx", IsWrapped=true)]
    public partial class cfdiPorUUIDv33Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uuid;
        
        public cfdiPorUUIDv33Request() {
        }
        
        public cfdiPorUUIDv33Request(string contrato, string usuario, string passwd, string uuid) {
            this.contrato = contrato;
            this.usuario = usuario;
            this.passwd = passwd;
            this.uuid = uuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cfdiPorUUIDv33Response", WrapperNamespace="http://recepcionCfdi.ws.pade.mx", IsWrapped=true)]
    public partial class cfdiPorUUIDv33Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public cfdiPorUUIDv33Response() {
        }
        
        public cfdiPorUUIDv33Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cfdiPorEtiquetav33", WrapperNamespace="http://recepcionCfdi.ws.pade.mx", IsWrapped=true)]
    public partial class cfdiPorEtiquetav33Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string etiqueta;
        
        public cfdiPorEtiquetav33Request() {
        }
        
        public cfdiPorEtiquetav33Request(string contrato, string usuario, string passwd, string etiqueta) {
            this.contrato = contrato;
            this.usuario = usuario;
            this.passwd = passwd;
            this.etiqueta = etiqueta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cfdiPorEtiquetav33Response", WrapperNamespace="http://recepcionCfdi.ws.pade.mx", IsWrapped=true)]
    public partial class cfdiPorEtiquetav33Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcionCfdi.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public cfdiPorEtiquetav33Response() {
        }
        
        public cfdiPorEtiquetav33Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RecepcionCfdiChannel : UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecepcionCfdiClient : System.ServiceModel.ClientBase<UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi>, UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi {
        
        public RecepcionCfdiClient() {
        }
        
        public RecepcionCfdiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecepcionCfdiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecepcionCfdiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecepcionCfdiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorQRCodev33Response UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi.verificacionPorQRCodev33(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorQRCodev33Request request) {
            return base.Channel.verificacionPorQRCodev33(request);
        }
        
        public string verificacionPorQRCodev33(string contrato, string usuario, string passwd, string qrCode) {
            UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorQRCodev33Request inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorQRCodev33Request();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.qrCode = qrCode;
            UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorQRCodev33Response retVal = ((UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi)(this)).verificacionPorQRCodev33(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorQRCodev33Response> UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi.verificacionPorQRCodev33Async(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorQRCodev33Request request) {
            return base.Channel.verificacionPorQRCodev33Async(request);
        }
        
        public System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorQRCodev33Response> verificacionPorQRCodev33Async(string contrato, string usuario, string passwd, string qrCode) {
            UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorQRCodev33Request inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorQRCodev33Request();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.qrCode = qrCode;
            return ((UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi)(this)).verificacionPorQRCodev33Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorXMLv33Response UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi.verificacionPorXMLv33(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorXMLv33Request request) {
            return base.Channel.verificacionPorXMLv33(request);
        }
        
        public string verificacionPorXMLv33(string contrato, string usuario, string passwd, string cfdiXml) {
            UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorXMLv33Request inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorXMLv33Request();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.cfdiXml = cfdiXml;
            UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorXMLv33Response retVal = ((UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi)(this)).verificacionPorXMLv33(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorXMLv33Response> UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi.verificacionPorXMLv33Async(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorXMLv33Request request) {
            return base.Channel.verificacionPorXMLv33Async(request);
        }
        
        public System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorXMLv33Response> verificacionPorXMLv33Async(string contrato, string usuario, string passwd, string cfdiXml) {
            UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorXMLv33Request inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.verificacionPorXMLv33Request();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.cfdiXml = cfdiXml;
            return ((UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi)(this)).verificacionPorXMLv33Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiMultipleResponse UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi.recepcionCfdiMultiple(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiMultipleRequest request) {
            return base.Channel.recepcionCfdiMultiple(request);
        }
        
        public string recepcionCfdiMultiple(string contrato, string usuario, string passwd, string[] arregloCfdiXml, string[] etiquetas, bool prueba, string[] opciones) {
            UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiMultipleRequest inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiMultipleRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.arregloCfdiXml = arregloCfdiXml;
            inValue.etiquetas = etiquetas;
            inValue.prueba = prueba;
            inValue.opciones = opciones;
            UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiMultipleResponse retVal = ((UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi)(this)).recepcionCfdiMultiple(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiMultipleResponse> UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi.recepcionCfdiMultipleAsync(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiMultipleRequest request) {
            return base.Channel.recepcionCfdiMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiMultipleResponse> recepcionCfdiMultipleAsync(string contrato, string usuario, string passwd, string[] arregloCfdiXml, string[] etiquetas, bool prueba, string[] opciones) {
            UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiMultipleRequest inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiMultipleRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.arregloCfdiXml = arregloCfdiXml;
            inValue.etiquetas = etiquetas;
            inValue.prueba = prueba;
            inValue.opciones = opciones;
            return ((UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi)(this)).recepcionCfdiMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiResponse UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi.recepcionCfdi(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiRequest request) {
            return base.Channel.recepcionCfdi(request);
        }
        
        public string recepcionCfdi(string contrato, string usuario, string passwd, string cfdiXml, string etiqueta, bool prueba, string[] opciones) {
            UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiRequest inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.cfdiXml = cfdiXml;
            inValue.etiqueta = etiqueta;
            inValue.prueba = prueba;
            inValue.opciones = opciones;
            UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiResponse retVal = ((UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi)(this)).recepcionCfdi(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiResponse> UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi.recepcionCfdiAsync(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiRequest request) {
            return base.Channel.recepcionCfdiAsync(request);
        }
        
        public System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiResponse> recepcionCfdiAsync(string contrato, string usuario, string passwd, string cfdiXml, string etiqueta, bool prueba, string[] opciones) {
            UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiRequest inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.cfdiXml = cfdiXml;
            inValue.etiqueta = etiqueta;
            inValue.prueba = prueba;
            inValue.opciones = opciones;
            return ((UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi)(this)).recepcionCfdiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiZipResponse UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi.recepcionCfdiZip(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiZipRequest request) {
            return base.Channel.recepcionCfdiZip(request);
        }
        
        public string recepcionCfdiZip(string contrato, string usuario, string passwd, byte[] archivo, bool prueba, string[] opciones) {
            UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiZipRequest inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiZipRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.archivo = archivo;
            inValue.prueba = prueba;
            inValue.opciones = opciones;
            UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiZipResponse retVal = ((UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi)(this)).recepcionCfdiZip(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiZipResponse> UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi.recepcionCfdiZipAsync(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiZipRequest request) {
            return base.Channel.recepcionCfdiZipAsync(request);
        }
        
        public System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiZipResponse> recepcionCfdiZipAsync(string contrato, string usuario, string passwd, byte[] archivo, bool prueba, string[] opciones) {
            UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiZipRequest inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.recepcionCfdiZipRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.archivo = archivo;
            inValue.prueba = prueba;
            inValue.opciones = opciones;
            return ((UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi)(this)).recepcionCfdiZipAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorUUIDv33Response UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi.cfdiPorUUIDv33(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorUUIDv33Request request) {
            return base.Channel.cfdiPorUUIDv33(request);
        }
        
        public string cfdiPorUUIDv33(string contrato, string usuario, string passwd, string uuid) {
            UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorUUIDv33Request inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorUUIDv33Request();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.uuid = uuid;
            UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorUUIDv33Response retVal = ((UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi)(this)).cfdiPorUUIDv33(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorUUIDv33Response> UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi.cfdiPorUUIDv33Async(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorUUIDv33Request request) {
            return base.Channel.cfdiPorUUIDv33Async(request);
        }
        
        public System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorUUIDv33Response> cfdiPorUUIDv33Async(string contrato, string usuario, string passwd, string uuid) {
            UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorUUIDv33Request inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorUUIDv33Request();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.uuid = uuid;
            return ((UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi)(this)).cfdiPorUUIDv33Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorEtiquetav33Response UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi.cfdiPorEtiquetav33(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorEtiquetav33Request request) {
            return base.Channel.cfdiPorEtiquetav33(request);
        }
        
        public string cfdiPorEtiquetav33(string contrato, string usuario, string passwd, string etiqueta) {
            UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorEtiquetav33Request inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorEtiquetav33Request();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.etiqueta = etiqueta;
            UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorEtiquetav33Response retVal = ((UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi)(this)).cfdiPorEtiquetav33(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorEtiquetav33Response> UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi.cfdiPorEtiquetav33Async(UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorEtiquetav33Request request) {
            return base.Channel.cfdiPorEtiquetav33Async(request);
        }
        
        public System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorEtiquetav33Response> cfdiPorEtiquetav33Async(string contrato, string usuario, string passwd, string etiqueta) {
            UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorEtiquetav33Request inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.cfdiPorEtiquetav33Request();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.etiqueta = etiqueta;
            return ((UGRS.AddOn.PurchaseInvoice.RecepcionCfdiService.RecepcionCfdi)(this)).cfdiPorEtiquetav33Async(inValue);
        }
    }
}
