// <auto-generated />
namespace UGRS.Data.Auctions.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FoodChargeCorrection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FoodChargeCorrection));
        
        string IMigrationMetadata.Id
        {
            get { return "201710280032181_FoodChargeCorrection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
