// <auto-generated />
namespace UGRS.Data.Auctions.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InvoiceFields_Payments_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InvoiceFields_Payments_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201808301846188_InvoiceFields_Payments_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
