//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGRS.AddOn.PurchaseInvoice.RecepcionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://recepcion.ws.pade.mx", ConfigurationName="RecepcionService.Recepcion")]
    public interface Recepcion {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcion.ws.pade.mx/Recepcion/cfdiPorUUIDRequest", ReplyAction="http://recepcion.ws.pade.mx/Recepcion/cfdiPorUUIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorUUIDResponse cfdiPorUUID(UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorUUIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcion.ws.pade.mx/Recepcion/cfdiPorUUIDRequest", ReplyAction="http://recepcion.ws.pade.mx/Recepcion/cfdiPorUUIDResponse")]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorUUIDResponse> cfdiPorUUIDAsync(UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorUUIDRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcion.ws.pade.mx/Recepcion/recepcionRequest", ReplyAction="http://recepcion.ws.pade.mx/Recepcion/recepcionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionResponse recepcion(UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcion.ws.pade.mx/Recepcion/recepcionRequest", ReplyAction="http://recepcion.ws.pade.mx/Recepcion/recepcionResponse")]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionResponse> recepcionAsync(UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcion.ws.pade.mx/Recepcion/verificacionPorXMLRequest", ReplyAction="http://recepcion.ws.pade.mx/Recepcion/verificacionPorXMLResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorXMLResponse verificacionPorXML(UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcion.ws.pade.mx/Recepcion/verificacionPorXMLRequest", ReplyAction="http://recepcion.ws.pade.mx/Recepcion/verificacionPorXMLResponse")]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorXMLResponse> verificacionPorXMLAsync(UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorXMLRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcion.ws.pade.mx/Recepcion/verificacionPorQRCodeRequest", ReplyAction="http://recepcion.ws.pade.mx/Recepcion/verificacionPorQRCodeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorQRCodeResponse verificacionPorQRCode(UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorQRCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcion.ws.pade.mx/Recepcion/verificacionPorQRCodeRequest", ReplyAction="http://recepcion.ws.pade.mx/Recepcion/verificacionPorQRCodeResponse")]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorQRCodeResponse> verificacionPorQRCodeAsync(UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorQRCodeRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcion.ws.pade.mx/Recepcion/recepcionMultipleRequest", ReplyAction="http://recepcion.ws.pade.mx/Recepcion/recepcionMultipleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionMultipleResponse recepcionMultiple(UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionMultipleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcion.ws.pade.mx/Recepcion/recepcionMultipleRequest", ReplyAction="http://recepcion.ws.pade.mx/Recepcion/recepcionMultipleResponse")]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionMultipleResponse> recepcionMultipleAsync(UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionMultipleRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcion.ws.pade.mx/Recepcion/recepcionArchivoZipRequest", ReplyAction="http://recepcion.ws.pade.mx/Recepcion/recepcionArchivoZipResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionArchivoZipResponse recepcionArchivoZip(UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionArchivoZipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcion.ws.pade.mx/Recepcion/recepcionArchivoZipRequest", ReplyAction="http://recepcion.ws.pade.mx/Recepcion/recepcionArchivoZipResponse")]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionArchivoZipResponse> recepcionArchivoZipAsync(UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionArchivoZipRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcion.ws.pade.mx/Recepcion/cfdiPorEtiquetaRequest", ReplyAction="http://recepcion.ws.pade.mx/Recepcion/cfdiPorEtiquetaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorEtiquetaResponse cfdiPorEtiqueta(UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorEtiquetaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://recepcion.ws.pade.mx/Recepcion/cfdiPorEtiquetaRequest", ReplyAction="http://recepcion.ws.pade.mx/Recepcion/cfdiPorEtiquetaResponse")]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorEtiquetaResponse> cfdiPorEtiquetaAsync(UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorEtiquetaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cfdiPorUUID", WrapperNamespace="http://recepcion.ws.pade.mx", IsWrapped=true)]
    public partial class cfdiPorUUIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uuid;
        
        public cfdiPorUUIDRequest() {
        }
        
        public cfdiPorUUIDRequest(string contrato, string usuario, string passwd, string uuid) {
            this.contrato = contrato;
            this.usuario = usuario;
            this.passwd = passwd;
            this.uuid = uuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cfdiPorUUIDResponse", WrapperNamespace="http://recepcion.ws.pade.mx", IsWrapped=true)]
    public partial class cfdiPorUUIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public cfdiPorUUIDResponse() {
        }
        
        public cfdiPorUUIDResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcion", WrapperNamespace="http://recepcion.ws.pade.mx", IsWrapped=true)]
    public partial class recepcionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cfdiXml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string etiqueta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool prueba;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] opciones;
        
        public recepcionRequest() {
        }
        
        public recepcionRequest(string contrato, string usuario, string passwd, string cfdiXml, string etiqueta, bool prueba, string[] opciones) {
            this.contrato = contrato;
            this.usuario = usuario;
            this.passwd = passwd;
            this.cfdiXml = cfdiXml;
            this.etiqueta = etiqueta;
            this.prueba = prueba;
            this.opciones = opciones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionResponse", WrapperNamespace="http://recepcion.ws.pade.mx", IsWrapped=true)]
    public partial class recepcionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public recepcionResponse() {
        }
        
        public recepcionResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificacionPorXML", WrapperNamespace="http://recepcion.ws.pade.mx", IsWrapped=true)]
    public partial class verificacionPorXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cfdiXml;
        
        public verificacionPorXMLRequest() {
        }
        
        public verificacionPorXMLRequest(string contrato, string usuario, string passwd, string cfdiXml) {
            this.contrato = contrato;
            this.usuario = usuario;
            this.passwd = passwd;
            this.cfdiXml = cfdiXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificacionPorXMLResponse", WrapperNamespace="http://recepcion.ws.pade.mx", IsWrapped=true)]
    public partial class verificacionPorXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public verificacionPorXMLResponse() {
        }
        
        public verificacionPorXMLResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificacionPorQRCode", WrapperNamespace="http://recepcion.ws.pade.mx", IsWrapped=true)]
    public partial class verificacionPorQRCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string qrCode;
        
        public verificacionPorQRCodeRequest() {
        }
        
        public verificacionPorQRCodeRequest(string contrato, string usuario, string passwd, string qrCode) {
            this.contrato = contrato;
            this.usuario = usuario;
            this.passwd = passwd;
            this.qrCode = qrCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificacionPorQRCodeResponse", WrapperNamespace="http://recepcion.ws.pade.mx", IsWrapped=true)]
    public partial class verificacionPorQRCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public verificacionPorQRCodeResponse() {
        }
        
        public verificacionPorQRCodeResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionMultiple", WrapperNamespace="http://recepcion.ws.pade.mx", IsWrapped=true)]
    public partial class recepcionMultipleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("arregloCfdiXml", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] arregloCfdiXml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("etiquetas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] etiquetas;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool prueba;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] opciones;
        
        public recepcionMultipleRequest() {
        }
        
        public recepcionMultipleRequest(string contrato, string usuario, string passwd, string[] arregloCfdiXml, string[] etiquetas, bool prueba, string[] opciones) {
            this.contrato = contrato;
            this.usuario = usuario;
            this.passwd = passwd;
            this.arregloCfdiXml = arregloCfdiXml;
            this.etiquetas = etiquetas;
            this.prueba = prueba;
            this.opciones = opciones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionMultipleResponse", WrapperNamespace="http://recepcion.ws.pade.mx", IsWrapped=true)]
    public partial class recepcionMultipleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public recepcionMultipleResponse() {
        }
        
        public recepcionMultipleResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionArchivoZip", WrapperNamespace="http://recepcion.ws.pade.mx", IsWrapped=true)]
    public partial class recepcionArchivoZipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] archivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool prueba;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] opciones;
        
        public recepcionArchivoZipRequest() {
        }
        
        public recepcionArchivoZipRequest(string contrato, string usuario, string passwd, byte[] archivo, bool prueba, string[] opciones) {
            this.contrato = contrato;
            this.usuario = usuario;
            this.passwd = passwd;
            this.archivo = archivo;
            this.prueba = prueba;
            this.opciones = opciones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionArchivoZipResponse", WrapperNamespace="http://recepcion.ws.pade.mx", IsWrapped=true)]
    public partial class recepcionArchivoZipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public recepcionArchivoZipResponse() {
        }
        
        public recepcionArchivoZipResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cfdiPorEtiqueta", WrapperNamespace="http://recepcion.ws.pade.mx", IsWrapped=true)]
    public partial class cfdiPorEtiquetaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string etiqueta;
        
        public cfdiPorEtiquetaRequest() {
        }
        
        public cfdiPorEtiquetaRequest(string contrato, string usuario, string passwd, string etiqueta) {
            this.contrato = contrato;
            this.usuario = usuario;
            this.passwd = passwd;
            this.etiqueta = etiqueta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cfdiPorEtiquetaResponse", WrapperNamespace="http://recepcion.ws.pade.mx", IsWrapped=true)]
    public partial class cfdiPorEtiquetaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recepcion.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public cfdiPorEtiquetaResponse() {
        }
        
        public cfdiPorEtiquetaResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RecepcionChannel : UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecepcionClient : System.ServiceModel.ClientBase<UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion>, UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion {
        
        public RecepcionClient() {
        }
        
        public RecepcionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecepcionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecepcionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecepcionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorUUIDResponse UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion.cfdiPorUUID(UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorUUIDRequest request) {
            return base.Channel.cfdiPorUUID(request);
        }
        
        public string cfdiPorUUID(string contrato, string usuario, string passwd, string uuid) {
            UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorUUIDRequest inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorUUIDRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.uuid = uuid;
            UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorUUIDResponse retVal = ((UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion)(this)).cfdiPorUUID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorUUIDResponse> UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion.cfdiPorUUIDAsync(UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorUUIDRequest request) {
            return base.Channel.cfdiPorUUIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorUUIDResponse> cfdiPorUUIDAsync(string contrato, string usuario, string passwd, string uuid) {
            UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorUUIDRequest inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorUUIDRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.uuid = uuid;
            return ((UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion)(this)).cfdiPorUUIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionResponse UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion.recepcion(UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionRequest request) {
            return base.Channel.recepcion(request);
        }
        
        public string recepcion(string contrato, string usuario, string passwd, string cfdiXml, string etiqueta, bool prueba, string[] opciones) {
            UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionRequest inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.cfdiXml = cfdiXml;
            inValue.etiqueta = etiqueta;
            inValue.prueba = prueba;
            inValue.opciones = opciones;
            UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionResponse retVal = ((UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion)(this)).recepcion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionResponse> UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion.recepcionAsync(UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionRequest request) {
            return base.Channel.recepcionAsync(request);
        }
        
        public System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionResponse> recepcionAsync(string contrato, string usuario, string passwd, string cfdiXml, string etiqueta, bool prueba, string[] opciones) {
            UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionRequest inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.cfdiXml = cfdiXml;
            inValue.etiqueta = etiqueta;
            inValue.prueba = prueba;
            inValue.opciones = opciones;
            return ((UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion)(this)).recepcionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorXMLResponse UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion.verificacionPorXML(UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorXMLRequest request) {
            return base.Channel.verificacionPorXML(request);
        }
        
        public string verificacionPorXML(string contrato, string usuario, string passwd, string cfdiXml) {
            UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorXMLRequest inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorXMLRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.cfdiXml = cfdiXml;
            UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorXMLResponse retVal = ((UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion)(this)).verificacionPorXML(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorXMLResponse> UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion.verificacionPorXMLAsync(UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorXMLRequest request) {
            return base.Channel.verificacionPorXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorXMLResponse> verificacionPorXMLAsync(string contrato, string usuario, string passwd, string cfdiXml) {
            UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorXMLRequest inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorXMLRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.cfdiXml = cfdiXml;
            return ((UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion)(this)).verificacionPorXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorQRCodeResponse UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion.verificacionPorQRCode(UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorQRCodeRequest request) {
            return base.Channel.verificacionPorQRCode(request);
        }
        
        public string verificacionPorQRCode(string contrato, string usuario, string passwd, string qrCode) {
            UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorQRCodeRequest inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorQRCodeRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.qrCode = qrCode;
            UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorQRCodeResponse retVal = ((UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion)(this)).verificacionPorQRCode(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorQRCodeResponse> UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion.verificacionPorQRCodeAsync(UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorQRCodeRequest request) {
            return base.Channel.verificacionPorQRCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorQRCodeResponse> verificacionPorQRCodeAsync(string contrato, string usuario, string passwd, string qrCode) {
            UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorQRCodeRequest inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionService.verificacionPorQRCodeRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.qrCode = qrCode;
            return ((UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion)(this)).verificacionPorQRCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionMultipleResponse UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion.recepcionMultiple(UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionMultipleRequest request) {
            return base.Channel.recepcionMultiple(request);
        }
        
        public string recepcionMultiple(string contrato, string usuario, string passwd, string[] arregloCfdiXml, string[] etiquetas, bool prueba, string[] opciones) {
            UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionMultipleRequest inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionMultipleRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.arregloCfdiXml = arregloCfdiXml;
            inValue.etiquetas = etiquetas;
            inValue.prueba = prueba;
            inValue.opciones = opciones;
            UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionMultipleResponse retVal = ((UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion)(this)).recepcionMultiple(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionMultipleResponse> UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion.recepcionMultipleAsync(UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionMultipleRequest request) {
            return base.Channel.recepcionMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionMultipleResponse> recepcionMultipleAsync(string contrato, string usuario, string passwd, string[] arregloCfdiXml, string[] etiquetas, bool prueba, string[] opciones) {
            UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionMultipleRequest inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionMultipleRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.arregloCfdiXml = arregloCfdiXml;
            inValue.etiquetas = etiquetas;
            inValue.prueba = prueba;
            inValue.opciones = opciones;
            return ((UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion)(this)).recepcionMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionArchivoZipResponse UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion.recepcionArchivoZip(UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionArchivoZipRequest request) {
            return base.Channel.recepcionArchivoZip(request);
        }
        
        public string recepcionArchivoZip(string contrato, string usuario, string passwd, byte[] archivo, bool prueba, string[] opciones) {
            UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionArchivoZipRequest inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionArchivoZipRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.archivo = archivo;
            inValue.prueba = prueba;
            inValue.opciones = opciones;
            UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionArchivoZipResponse retVal = ((UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion)(this)).recepcionArchivoZip(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionArchivoZipResponse> UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion.recepcionArchivoZipAsync(UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionArchivoZipRequest request) {
            return base.Channel.recepcionArchivoZipAsync(request);
        }
        
        public System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionArchivoZipResponse> recepcionArchivoZipAsync(string contrato, string usuario, string passwd, byte[] archivo, bool prueba, string[] opciones) {
            UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionArchivoZipRequest inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionService.recepcionArchivoZipRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.archivo = archivo;
            inValue.prueba = prueba;
            inValue.opciones = opciones;
            return ((UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion)(this)).recepcionArchivoZipAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorEtiquetaResponse UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion.cfdiPorEtiqueta(UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorEtiquetaRequest request) {
            return base.Channel.cfdiPorEtiqueta(request);
        }
        
        public string cfdiPorEtiqueta(string contrato, string usuario, string passwd, string etiqueta) {
            UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorEtiquetaRequest inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorEtiquetaRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.etiqueta = etiqueta;
            UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorEtiquetaResponse retVal = ((UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion)(this)).cfdiPorEtiqueta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorEtiquetaResponse> UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion.cfdiPorEtiquetaAsync(UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorEtiquetaRequest request) {
            return base.Channel.cfdiPorEtiquetaAsync(request);
        }
        
        public System.Threading.Tasks.Task<UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorEtiquetaResponse> cfdiPorEtiquetaAsync(string contrato, string usuario, string passwd, string etiqueta) {
            UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorEtiquetaRequest inValue = new UGRS.AddOn.PurchaseInvoice.RecepcionService.cfdiPorEtiquetaRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.etiqueta = etiqueta;
            return ((UGRS.AddOn.PurchaseInvoice.RecepcionService.Recepcion)(this)).cfdiPorEtiquetaAsync(inValue);
        }
    }
}
